@startuml

Person <|-- Student

class Person {
    - name: String
    
    
    + Person(n:String)
    + getName():String
}

class Student {
    - matrnr: int

    + Student(m:int,n:String)
    + getMatrNr():int
}

@enduml